apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-xs6w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-xs6w
    app.kubernetes.io/part-of: e2e-dotnet
  name: devfile-sample-dotnet60-basic-xs6w
  namespace: e2e-demos-qmkv-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-xs6w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-xs6w
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:f584a414940b7f994894903f8e80671aa5f8a1b72c0cfd82d7ee633e69c54850
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
