apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-xs6w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-xs6w
    app.kubernetes.io/part-of: e2e-dotnet
  name: devfile-sample-dotnet60-basic-xs6w
  namespace: e2e-demos-qmkv-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-dotnet60-basic-xs6w
    weight: null
status: {}
